# Generated by Django 4.0.10 on 2024-02-29 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("account", "0010_alter_customuser_expire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="expire_date",
            field=models.DateField(default=datetime.date(2025, 12, 29)),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
    ]
