version: '3.10'
services:
  backend:
    container_name: blog-container
    image: blogimage
    build: .
    expose:
      - 8000
    command: gunicorn Core.wsgi --bind 0.0.0.0:8000
    depends_on:
      - redis
      - database
    environment:
      - DEBUG=False

    volumes:
      - .:/app
      - static_volume:/app/static/
      - media_volume:/app/media/
  database:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  # smtp4dev service    
  # smtp4dev:
  #   image: rnwood/smtp4dev:v3
  #   restart: always
  #   ports:
  #     - '5000:80'
  #     - '25:25'
  #     - '143:143'
  #   volumes:
  #     - smtp4dev-data:/smtp4dev
  #   environment:
  #     - ServerOptions__HostName=smtp4dev
  # redis service    
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    privileged: true
  # worker

  worker:
    build: .
    command: celery -A Core worker -l info
    depends_on:
      - redis
      - backend

    volumes:
      - .:/app
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
    depends_on:
      - redis
      - backend
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static/
      - media_volume:/home/app/media/

volumes:
  postgres_data: # smtp4dev-data:
  static_volume:
  media_volume:


