# Generated by Django 4.0.10 on 2024-02-29 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0006_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply_count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="expire_date",
            field=models.DateField(default=datetime.date(2025, 12, 29)),
        ),
    ]
