# Generated by Django 4.0.10 on 2024-02-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0007_comment_reply_count_alter_blog_expire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="reply_count",
            field=models.IntegerField(default=0),
        ),
    ]
