name: Blog Test & Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Test:
    name: Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Composer
      run: docker-compose up -d
    - name: testing with pytest
      run: docker-compose exec -T backend sh -c "flake8 && pytest ."

  Deploy:
    if: ${{ always() && contains(join(needs.*.result,','),'SUCCESS')}}
    name: Deploy 
    needs: Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: command deploy
      uses: appleboy/ssh-action@master
      with:
         username: ${{secrets.USERNAME}}
         password: ${{secrets.PASSWORD}}
         host: ${{secrets.HOST}}
         port: ${{secrets.PORT}}
         script:
          cd ${{secrets.PROJECTPATH}}
          docker-compose -f docker-compose-stage.yml stop
          git pull
          docker-compose -f docker-compose-stage.yml restart
   
      
         
