name: Blog Test & Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Test:
    name: Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Composer
      run: docker-compose up -d
    - name: testing with pytest
      run: docker-compose exec -T backend sh -c "flake8 && pytest ."

  Deploy:
    name: Deploy 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: command deploy
      uses: appleboy/ssh-action@master
    with:
     Username: ${{secrets.USERNAME}}
     Password: ${{secrets.PASSWORD}}
     Host: ${{secrets.HOST}}
     Port: ${{secrets.PORT}}
     script: ls    
 
      
         
